######################################################################
# Automatically generated by qmake (3.0) ? 3 20 20:46:23 2014
######################################################################

TEMPLATE = app
TARGET = sprite_editor
INCLUDEPATH += .

# Input
HEADERS += sprite_editor.h
FORMS += sprite_editor.ui untitled.ui
SOURCES += sprite_editor.cpp
