######################################################################
# Automatically generated by qmake (3.0) ? 3 20 20:46:23 2014
######################################################################

TEMPLATE = app
TARGET = sprite_editor
INCLUDEPATH += .

# Input
CONFIG += qt debug
HEADERS += sprite_editor.h sprite_editor_core.h
FORMS += sprite_editor.ui untitled.ui
SOURCES += sprite_editor.cpp
LIBS += C:\usr\local\qt5\qtbase\lib\Qt5Widgetsd.lib
